"""Rust drop-in replacement for the C tet_index extension.

Auto-generated by iref3d/data/install_rust_backend.py.
Imports tet_index_series, tet_degree_x2, poly_convolve from the Rust
iref3d_core module instead of the C extension.
"""
import sys as _sys

# Add Rust lib to path if needed
_rust_lib = "/Users/pmp/Documents/Research/iref3d/core/target/release"
if _rust_lib not in _sys.path:
    _sys.path.insert(0, _rust_lib)

from iref3d_core import tet_index_series, tet_degree_x2, poly_convolve
